language: java
dist: xenial
env:
- global:
  - secure: blfVbUP0CdW+NC8i9NIHTttjuJ7hxAA3E9A0NoEfHirdH3whuQajqTgzFNyzknXd9tmE7srdmOMgv22fDNWqCCF6PfcraGkm6cEelEjVXKn4aqyPjjXFaiP/snnC+fd641vADq8yLt28bP1AGQlFknYPBCD60uYwTKHbIIop7KNJ1ratnsd95VmOrZQ08pNSVZ6za+XCva4ArnrTxDtcAgEaBktrPLNxRh1SeovromRRFrRb85+Z9V3p/GTIGo5jprJhlKH7388yn2I4WiLu3guEoIMH6WvmbUmWxxeMvI8WPJ2SkKCcCIcP6BwT10sU2YPii4MvumPep6zK3FrTOpnRpQUcXsyCZA9kKWnArDeMNidZs0oyRyAWtOl+RAQcct8dXhreFrvy1n8nkRyhJ+TJu0CMdvmhGixUu8KD/0UT4PHHBNbISwImtEskA6wUJNHlJOvS+ge+Szt/WOgAhn93Vzc7Sdgh6Do0wkHa758U56HIbDFNKhMEXGCZh0S0kcJwXzAnXyk/xJQ22X/g5qvy8NOLWRgWGH9iAu3HaHLH3LKoiKm2XTcwXIviizo3huYAgz8oI4ilgriYQ8tFJwzatmQIwIsGlHAd3vsflEtaayLyFtkz3fxeLLQ7//TbTtFPGxccjjyg+qUXv4qos1SD6A8PBux7y+/aVLEvrfM=
script:
- bash scripts/build_sdk.sh $TRAVIS_BUILD_NUMBER
branches:
  only:
  - master
deploy:
  provider: script
  script: bash scripts/push_sdk.sh $TRAVIS_BUILD_NUMBER
  on:
    branch: master
  skip_cleanup: true
notifications:
  slack:
    secure: LT/jd+gc/8YMv1eHvY50litiZA9BEl84sj0yuUzgZJ6A3xKCV/PqlfzLjkv2kn75yQA6ri3Rf2fONEMA5AMA+X+6GppAXRSnJGEH+R31bSJopIGRRSP51JqO3VDygWHMBUUPB1Uw/4QZg5UuDdkccgIbIH/QSvwLxZ2ho86YrBXuqDIY5X9WAh2PS+0loQtK3GHpkAEE5r6btoFnHJDCprJXac4GKFokxXFirlwCvuSDPtTEbn/W6MjeQQpR1JELG8XHh1EQxBlwSCcv6jL0mRoEF61mbWh880mrccwG60GfWV1FmVfH0Xb3CGjYmrBldA/emyHFF/gDoydp6FdEuzVPM4hCCg/l3nZ9U4gY4RyxEXZum0yJ4QVpklFGcJa8QjXszY2jR3Ud7FC4QEGKqvZnjUn4YVkEItIQm80Ttq/bYXh4YbF8TcY1uNTQYWKwIsaRtiHWPFnAGbD7mnmR19lhjdW214pNehWe2Ghnsq9VMkhCi8CcsbdTz4DlG+qobk11Ew0b7o0M2o5Re7/wj8/+0O+0zhWTqfknquFdmOc2t5afszwM721QxCgnbcnE2voZzD+E8JBHzhItCciD/CKovS2S6856+rGjAax5o058JcrMPWNR1UxVbSaxupCSgospk/xwU9hnoDxI0oHVkKmLjYiqjkFdQ7KTxJD0uNY=
