language: java
dist: xenial

env:
  - global:
      - secure: "blfVbUP0CdW+NC8i9NIHTttjuJ7hxAA3E9A0NoEfHirdH3whuQajqTgzFNyzknXd9tmE7srdmOMgv22fDNWqCCF6PfcraGkm6cEelEjVXKn4aqyPjjXFaiP/snnC+fd641vADq8yLt28bP1AGQlFknYPBCD60uYwTKHbIIop7KNJ1ratnsd95VmOrZQ08pNSVZ6za+XCva4ArnrTxDtcAgEaBktrPLNxRh1SeovromRRFrRb85+Z9V3p/GTIGo5jprJhlKH7388yn2I4WiLu3guEoIMH6WvmbUmWxxeMvI8WPJ2SkKCcCIcP6BwT10sU2YPii4MvumPep6zK3FrTOpnRpQUcXsyCZA9kKWnArDeMNidZs0oyRyAWtOl+RAQcct8dXhreFrvy1n8nkRyhJ+TJu0CMdvmhGixUu8KD/0UT4PHHBNbISwImtEskA6wUJNHlJOvS+ge+Szt/WOgAhn93Vzc7Sdgh6Do0wkHa758U56HIbDFNKhMEXGCZh0S0kcJwXzAnXyk/xJQ22X/g5qvy8NOLWRgWGH9iAu3HaHLH3LKoiKm2XTcwXIviizo3huYAgz8oI4ilgriYQ8tFJwzatmQIwIsGlHAd3vsflEtaayLyFtkz3fxeLLQ7//TbTtFPGxccjjyg+qUXv4qos1SD6A8PBux7y+/aVLEvrfM="

script:
  - ./gradlew :build-python:generateClient -Dorg.gradle.project.buildNumber=$TRAVIS_BUILD_NUMBER
  - ./gradlew :build-java:generateClient

branches:
  only:
    - master

deploy:
  provider: script
  script: bash scripts/push_sdk.sh
  on:
    branch: master
  skip_cleanup: true

notifications:
  slack:
    secure: kQaTYS7GluRh+oQY5gK1wl7V0j/Sn4NSlC31fSm8A/Qz2bBdP+3L7+757K2kXzqUaKl2muyUpMKvsvzZ+tU3Zjx5w2qnyvBU2vsEysae8h2VmIgp1Q+N+cORWCfLtEmv64VTf3/rMs8DyA04zREfVPtqIUMHh0Ul0yYEyPMWRstY2U8aMZglHYnv1/eHdCDnLHzPuUBOvzN3EeZY80PO/r0lq7+2NY5f3afoCiEPXUzzuOy28Dd2oyEfGGf65TRe+BNU9vSAn49WwJLH/U22c3M60fbiwuA4E3JLMbyeP0JUnGGZ8lpFqm8e9xvR4/x9J7f974ri1pGlJsLD1Vo55ar7UtNhrqyJeQoxwncfpHEpo+VS4COc+PFU8PzZkVZAmZNlO73HToq1xLMZqQ+S2Kk39u6FAjNopIeGEb6BCy46lSme0vnQ5WRxteEIeW9T8oOEJhqO7ztmyKdO++zBcQw+XoozTiPXxsecJTCi28O+7OBoohGeVgdro/QebX5HZrNJ388FDO3slzTudR6QsJrcfM8QhhGadpUKUVm1P6BNwqGlpb3KvRySpbuGz7xlbL3jF6zSBgsaqH7oEurZBBOluHobTUksD/5W4ibl+KKu8APeENcwWjdmPVa5i7rOCFvzmoEKcFMqz+tuP+WKD3REuVit040xlTAjURXN0Lc=
